### PR TITLE
Heavy cleanup

### PR DESCRIPTION
**Pull request by rreusser**
Cleanup tasks performed:
- used `standardjs`
- got rid of gulpfile ([mdtex-cli](https://github.com/rreusser/mdtex-cli) works fine instead, but that should really disappear in favor of a better solution)
- split into individually requirable files
- updated `.travis.yml`
- merge #11
- added LICENSE
- modified copyright: "&copy; Scijs"

### CODE REVIEW

**Comment by rreusser** [comment]
@tab58 — I've merged your pull request into the `cleanup` branch and created this PR. I'd like to use this as a template for cementing some guidelines, so I'm glad to hear any feedback you might have!

I'm going to have to run, but the final task is to add documentation for rotg. There are also some special cases (like axpy with some arguments equal to zero or one) that could be handled more efficiently. 

Oh, and I updated the license also. Feedback welcome on that. It's come up a few times and it just hasn't really been cleaned up, but I think think the time has (more than) come to get a handle on this stuff. See: https://github.com/scijs/contributing/issues/16

**Comment by tab58** [comment]
LGTM
[LGTM](http://lgtm.in/i/MwCQCbseq)

**Comment by tab58** [comment]
Let me know if there needs to be better documentation. I couldn't figure out how to keep the description brief and still communicate what is needful.

**Comment by rreusser** [comment]
I think the real solution here is to add an API section that actually documents all functions in gory detail (rotg in particular since it's not like the others), but I guess there's no reason to hold this up in the mean time.

**Comment by rreusser** [comment]
Published a new version to npm. I think it'll prove necessary to expand the documentation section, but I think it's fine to get this out there.

**Pull request merged**
